language: go
go: 
 - 1.2
 - 1.3
 - release
 - tip

before_install:
 - export PATH=/home/travis/gopath/bin:$PATH

install:
 - go get .
 - go get github.com/smartystreets/goconvey/convey
 - go get code.google.com/p/go.tools/cmd/cover
 - go get github.com/mattn/goveralls
 - go install github.com/mattn/goveralls
 
script:
 - go test -covermode=count -coverprofile=profile.cov
 - goveralls -coverprofile=profile.cov -service=travis-ci